"""Add trial_attributes table.

Revision ID: v4.1.0.a
Revises: v3.2.0.a
Create Date: 2024-09-20 12:45:06.941011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'v4.1.0.a'
down_revision = 'v3.2.0.a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'trial_attributes',
        sa.Column('trial_attribute_id', sa.Integer(), nullable=False),
        sa.Column('trial_id', sa.Integer(), nullable=True),
        sa.Column('key', sa.String(length=512), nullable=True),
        sa.Column('value_json', sa.Text(), nullable=True),
        sa.Column(
            'attr_type',
            sa.Enum('USER', 'SYSTEM', name='trialattributetype'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], ),
        sa.PrimaryKeyConstraint('trial_attribute_id'),
        sa.UniqueConstraint('trial_id', 'key', 'attr_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_attributes')
    # ### end Alembic commands ###
